In [29]:
import numpy as np
import scipy.linalg

t = 5  # Transitions
p = 9  # Places

a_plus = np.zeros((t, p))
a_minus = np.zeros((t, p))

# Define input and output arcs
input_arcs = np.array([[0, 0], [0, 1], [1, 2], [1, 3], [2, 4], [2, 5], [3, 6], [3, 7], [4, 8]])
output_arcs = np.array([[0, 7], [0, 8], [1, 0], [2, 1], [2, 2], [3, 3], [3, 5], [4, 4], [4, 6]])

a_minus[tuple(input_arcs.T)] = 1
a_plus[tuple(output_arcs.T)] = 1

a = a_plus - a_minus
print(a)

[[-1. -1.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0. -1. -1.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0. -1. -1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1. -1. -1.  0.]
 [ 0.  0.  0.  0.  1.  0.  1.  0. -1.]]


In [30]:
# Vectors v (циклічність)
t_invariants = scipy.linalg.null_space(a)
print(t_invariants)

[[-0.4720571  -0.19992521  0.23282461  0.42399513  0.19117052]
 [ 0.57015452  0.29212166 -0.1359142   0.21654225  0.35245645]
 [-0.63641638  0.16818059 -0.21607766  0.01441214  0.2304898 ]
 [ 0.16435928 -0.3681058   0.44890227  0.40958299 -0.03931928]
 [ 0.04760906 -0.28374885 -0.42847863  0.08170189  0.51018052]
 [-0.11387092  0.74405109  0.07648676  0.1492525   0.07276573]
 [ 0.00095976  0.21989804  0.65128922 -0.1742888   0.17442198]
 [ 0.04952859  0.15604724 -0.12590019  0.73312429 -0.14097553]
 [ 0.04856883 -0.0638508   0.22281059 -0.09258691  0.6846025 ]]


In [31]:
# Vectors w (консервативність)
s_invariants = scipy.linalg.null_space(a.T)
print(s_invariants)

[[-0.4472136]
 [-0.4472136]
 [-0.4472136]
 [-0.4472136]
 [-0.4472136]]
